### ISSUE TITLE
BMX does not validate the MFA option

### ISSUE THREAD

**Issue by chris-redekop** [Brightspace/bmx#177]
This can lead to BMX crashing when the TOTP is entered into the MFA option field, without first choosing an MFA option.

Workaround: don't enter invalid data

```
Okta Password: 
MFA Required
0 - token:software:totp
Select an available MFA option: XXXXXX # I just entered a TOTP here 
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/Brightspace/bmx/saml/identityProviders/okta.(*OktaClient).doMfa(0xc0001aca50, 0xc000060240, 0x600, 0x84b160)
	C:/d2l/bmx/saml/identityProviders/okta/okta.go:265 +0x95f
github.com/Brightspace/bmx/saml/identityProviders/okta.(*OktaClient).Authenticate(0xc0001aca50, 0xc00008c914, 0x8, 0xc00008cae0, 0xe, 0xc00008c910, 0x3, 0xc00008c900, 0x0, 0xb, ...)
	C:/d2l/bmx/saml/identityProviders/okta/okta.go:110 +0x6f8
github.com/Brightspace/bmx.authenticate(0xc00008c910, 0x3, 0xc00008c914, 0x8, 0x0, 0x0, 0x0, 0xc00008cae0, 0xe, 0x0, ...)
	C:/d2l/bmx/console.go:68 +0x58e
github.com/Brightspace/bmx.Print(0x9d6060, 0xc0001aca50, 0xc00008c910, 0x3, 0xc00008c914, 0x8, 0x0, 0x0, 0x0, 0x0, ...)
	C:/d2l/bmx/print.go:47 +0x25c
main.glob..func1(0xcde020, 0xd01880, 0x0, 0x0)
	C:/d2l/bmx/cmd/bmx/print.go:42 +0x2bd
github.com/spf13/cobra.(*Command).execute(0xcde020, 0xd01880, 0x0, 0x0, 0xcde020, 0xd01880)
	C:/Users/cstavropoulos/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0xce4880, 0xc000153f78, 0x81d287, 0xce4880)
	C:/Users/cstavropoulos/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0xce4880, 0x0, 0x91b5a5)
	C:/Users/cstavropoulos/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800 +0x2b
main.main()
	C:/d2l/bmx/cmd/bmx/bmx.go:19 +0x2d
```

**Comment by boarnoah** [comment]
Fixed in rewrite (check select values to be within range).
